//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AppRepository", "ApplicationEntityApplicationVersionEntitylastAcceptedVersion", "ApplicationEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationEntity), "ApplicationVersionEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationVersionEntity))]
[assembly: EdmRelationshipAttribute("AppRepository", "ApplicationEntityApplicationVersionEntitylastCommitedVersion", "ApplicationEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationEntity), "ApplicationVersionEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationVersionEntity))]
[assembly: EdmRelationshipAttribute("AppRepository", "ApplicationEntityApplicationMetadataEntitylastAcceptedMetadata", "ApplicationEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationEntity), "ApplicationMetadataEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationMetadataEntity))]
[assembly: EdmRelationshipAttribute("AppRepository", "ApplicationEntityApplicationMetadataEntitylastCommitedMetadata", "ApplicationEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationEntity), "ApplicationMetadataEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppRepository.ApplicationMetadataEntity))]
[assembly: EdmRelationshipAttribute("AppRepository", "ApplicationAccountEntityApplicationEntityboughtApplicationsCollection", "ApplicationAccountEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppRepository.ApplicationAccountEntity), "ApplicationEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppRepository.ApplicationEntity))]
[assembly: EdmRelationshipAttribute("AppRepository", "ApplicationMetadataEntityCategoryEntitycategoriesCollection", "ApplicationMetadataEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppRepository.ApplicationMetadataEntity), "CategoryEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppRepository.CategoryEntity))]
[assembly: EdmRelationshipAttribute("AppRepository", "ApplicationVersionEntityStringfilePathsCollection", "ApplicationVersionEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AppRepository.ApplicationVersionEntity), "StringfilePathsEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppRepository.StringfilePathsEntity))]

#endregion

namespace AppRepository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AppRepositoryContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AppRepositoryContainer object using the connection string found in the 'AppRepositoryContainer' section of the application configuration file.
        /// </summary>
        public AppRepositoryContainer() : base("name=AppRepositoryContainer", "AppRepositoryContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppRepositoryContainer object.
        /// </summary>
        public AppRepositoryContainer(string connectionString) : base(connectionString, "AppRepositoryContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AppRepositoryContainer object.
        /// </summary>
        public AppRepositoryContainer(EntityConnection connection) : base(connection, "AppRepositoryContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationEntity> ApplicationEntitySet
        {
            get
            {
                if ((_ApplicationEntitySet == null))
                {
                    _ApplicationEntitySet = base.CreateObjectSet<ApplicationEntity>("ApplicationEntitySet");
                }
                return _ApplicationEntitySet;
            }
        }
        private ObjectSet<ApplicationEntity> _ApplicationEntitySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationAccountEntity> ApplicationAccountEntitySet
        {
            get
            {
                if ((_ApplicationAccountEntitySet == null))
                {
                    _ApplicationAccountEntitySet = base.CreateObjectSet<ApplicationAccountEntity>("ApplicationAccountEntitySet");
                }
                return _ApplicationAccountEntitySet;
            }
        }
        private ObjectSet<ApplicationAccountEntity> _ApplicationAccountEntitySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationMetadataEntity> ApplicationMetadataEntitySet
        {
            get
            {
                if ((_ApplicationMetadataEntitySet == null))
                {
                    _ApplicationMetadataEntitySet = base.CreateObjectSet<ApplicationMetadataEntity>("ApplicationMetadataEntitySet");
                }
                return _ApplicationMetadataEntitySet;
            }
        }
        private ObjectSet<ApplicationMetadataEntity> _ApplicationMetadataEntitySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationVersionEntity> ApplicationVersionEntitySet
        {
            get
            {
                if ((_ApplicationVersionEntitySet == null))
                {
                    _ApplicationVersionEntitySet = base.CreateObjectSet<ApplicationVersionEntity>("ApplicationVersionEntitySet");
                }
                return _ApplicationVersionEntitySet;
            }
        }
        private ObjectSet<ApplicationVersionEntity> _ApplicationVersionEntitySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoryEntity> CategoryEntitySet
        {
            get
            {
                if ((_CategoryEntitySet == null))
                {
                    _CategoryEntitySet = base.CreateObjectSet<CategoryEntity>("CategoryEntitySet");
                }
                return _CategoryEntitySet;
            }
        }
        private ObjectSet<CategoryEntity> _CategoryEntitySet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StringfilePathsEntity> StringfilePathsEntitySet
        {
            get
            {
                if ((_StringfilePathsEntitySet == null))
                {
                    _StringfilePathsEntitySet = base.CreateObjectSet<StringfilePathsEntity>("StringfilePathsEntitySet");
                }
                return _StringfilePathsEntitySet;
            }
        }
        private ObjectSet<StringfilePathsEntity> _StringfilePathsEntitySet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationEntitySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationEntitySet(ApplicationEntity applicationEntity)
        {
            base.AddObject("ApplicationEntitySet", applicationEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationAccountEntitySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationAccountEntitySet(ApplicationAccountEntity applicationAccountEntity)
        {
            base.AddObject("ApplicationAccountEntitySet", applicationAccountEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationMetadataEntitySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationMetadataEntitySet(ApplicationMetadataEntity applicationMetadataEntity)
        {
            base.AddObject("ApplicationMetadataEntitySet", applicationMetadataEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationVersionEntitySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationVersionEntitySet(ApplicationVersionEntity applicationVersionEntity)
        {
            base.AddObject("ApplicationVersionEntitySet", applicationVersionEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoryEntitySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoryEntitySet(CategoryEntity categoryEntity)
        {
            base.AddObject("CategoryEntitySet", categoryEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StringfilePathsEntitySet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStringfilePathsEntitySet(StringfilePathsEntity stringfilePathsEntity)
        {
            base.AddObject("StringfilePathsEntitySet", stringfilePathsEntity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppRepository", Name="ApplicationAccountEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationAccountEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationAccountEntity object.
        /// </summary>
        /// <param name="applicationAccountID">Initial value of the applicationAccountID property.</param>
        public static ApplicationAccountEntity CreateApplicationAccountEntity(global::System.Int32 applicationAccountID)
        {
            ApplicationAccountEntity applicationAccountEntity = new ApplicationAccountEntity();
            applicationAccountEntity.applicationAccountID = applicationAccountID;
            return applicationAccountEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accountUserName
        {
            get
            {
                return _accountUserName;
            }
            set
            {
                OnaccountUserNameChanging(value);
                ReportPropertyChanging("accountUserName");
                _accountUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accountUserName");
                OnaccountUserNameChanged();
            }
        }
        private global::System.String _accountUserName;
        partial void OnaccountUserNameChanging(global::System.String value);
        partial void OnaccountUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 applicationAccountID
        {
            get
            {
                return _applicationAccountID;
            }
            set
            {
                if (_applicationAccountID != value)
                {
                    OnapplicationAccountIDChanging(value);
                    ReportPropertyChanging("applicationAccountID");
                    _applicationAccountID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("applicationAccountID");
                    OnapplicationAccountIDChanged();
                }
            }
        }
        private global::System.Int32 _applicationAccountID;
        partial void OnapplicationAccountIDChanging(global::System.Int32 value);
        partial void OnapplicationAccountIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppRepository", "ApplicationAccountEntityApplicationEntityboughtApplicationsCollection", "ApplicationEntity")]
        public EntityCollection<ApplicationEntity> boughtApplications
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationEntity>("AppRepository.ApplicationAccountEntityApplicationEntityboughtApplicationsCollection", "ApplicationEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationEntity>("AppRepository.ApplicationAccountEntityApplicationEntityboughtApplicationsCollection", "ApplicationEntity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppRepository", Name="ApplicationEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationEntity object.
        /// </summary>
        /// <param name="applicationID">Initial value of the applicationID property.</param>
        public static ApplicationEntity CreateApplicationEntity(global::System.Int32 applicationID)
        {
            ApplicationEntity applicationEntity = new ApplicationEntity();
            applicationEntity.applicationID = applicationID;
            return applicationEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 applicationID
        {
            get
            {
                return _applicationID;
            }
            set
            {
                if (_applicationID != value)
                {
                    OnapplicationIDChanging(value);
                    ReportPropertyChanging("applicationID");
                    _applicationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("applicationID");
                    OnapplicationIDChanged();
                }
            }
        }
        private global::System.Int32 _applicationID;
        partial void OnapplicationIDChanging(global::System.Int32 value);
        partial void OnapplicationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creatorName
        {
            get
            {
                return _creatorName;
            }
            set
            {
                OncreatorNameChanging(value);
                ReportPropertyChanging("creatorName");
                _creatorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creatorName");
                OncreatorNameChanged();
            }
        }
        private global::System.String _creatorName;
        partial void OncreatorNameChanging(global::System.String value);
        partial void OncreatorNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppRepository", "ApplicationEntityApplicationVersionEntitylastAcceptedVersion", "ApplicationVersionEntity")]
        public ApplicationVersionEntity lastAcceptedVersion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastAcceptedVersion", "ApplicationVersionEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastAcceptedVersion", "ApplicationVersionEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationVersionEntity> lastAcceptedVersionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastAcceptedVersion", "ApplicationVersionEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastAcceptedVersion", "ApplicationVersionEntity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppRepository", "ApplicationEntityApplicationVersionEntitylastCommitedVersion", "ApplicationVersionEntity")]
        public ApplicationVersionEntity lastCommitedVersion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastCommitedVersion", "ApplicationVersionEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastCommitedVersion", "ApplicationVersionEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationVersionEntity> lastCommitedVersionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastCommitedVersion", "ApplicationVersionEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationVersionEntity>("AppRepository.ApplicationEntityApplicationVersionEntitylastCommitedVersion", "ApplicationVersionEntity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppRepository", "ApplicationEntityApplicationMetadataEntitylastAcceptedMetadata", "ApplicationMetadataEntity")]
        public ApplicationMetadataEntity lastAcceptedMetadata
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastAcceptedMetadata", "ApplicationMetadataEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastAcceptedMetadata", "ApplicationMetadataEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationMetadataEntity> lastAcceptedMetadataReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastAcceptedMetadata", "ApplicationMetadataEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastAcceptedMetadata", "ApplicationMetadataEntity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppRepository", "ApplicationEntityApplicationMetadataEntitylastCommitedMetadata", "ApplicationMetadataEntity")]
        public ApplicationMetadataEntity lastCommitedMetadata
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastCommitedMetadata", "ApplicationMetadataEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastCommitedMetadata", "ApplicationMetadataEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationMetadataEntity> lastCommitedMetadataReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastCommitedMetadata", "ApplicationMetadataEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationMetadataEntity>("AppRepository.ApplicationEntityApplicationMetadataEntitylastCommitedMetadata", "ApplicationMetadataEntity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppRepository", Name="ApplicationMetadataEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationMetadataEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationMetadataEntity object.
        /// </summary>
        /// <param name="applicationMetadataID">Initial value of the applicationMetadataID property.</param>
        public static ApplicationMetadataEntity CreateApplicationMetadataEntity(global::System.Int32 applicationMetadataID)
        {
            ApplicationMetadataEntity applicationMetadataEntity = new ApplicationMetadataEntity();
            applicationMetadataEntity.applicationMetadataID = applicationMetadataID;
            return applicationMetadataEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 applicationMetadataID
        {
            get
            {
                return _applicationMetadataID;
            }
            set
            {
                if (_applicationMetadataID != value)
                {
                    OnapplicationMetadataIDChanging(value);
                    ReportPropertyChanging("applicationMetadataID");
                    _applicationMetadataID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("applicationMetadataID");
                    OnapplicationMetadataIDChanged();
                }
            }
        }
        private global::System.Int32 _applicationMetadataID;
        partial void OnapplicationMetadataIDChanging(global::System.Int32 value);
        partial void OnapplicationMetadataIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _timestamp;
        partial void OntimestampChanging(Nullable<global::System.DateTime> value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Double> _price;
        partial void OnpriceChanging(Nullable<global::System.Double> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> acceptanceResult
        {
            get
            {
                return _acceptanceResult;
            }
            set
            {
                OnacceptanceResultChanging(value);
                ReportPropertyChanging("acceptanceResult");
                _acceptanceResult = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("acceptanceResult");
                OnacceptanceResultChanged();
            }
        }
        private Nullable<global::System.Int32> _acceptanceResult;
        partial void OnacceptanceResultChanging(Nullable<global::System.Int32> value);
        partial void OnacceptanceResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ageRestriction
        {
            get
            {
                return _ageRestriction;
            }
            set
            {
                OnageRestrictionChanging(value);
                ReportPropertyChanging("ageRestriction");
                _ageRestriction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ageRestriction");
                OnageRestrictionChanged();
            }
        }
        private Nullable<global::System.Int32> _ageRestriction;
        partial void OnageRestrictionChanging(Nullable<global::System.Int32> value);
        partial void OnageRestrictionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppRepository", "ApplicationMetadataEntityCategoryEntitycategoriesCollection", "CategoryEntity")]
        public EntityCollection<CategoryEntity> categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CategoryEntity>("AppRepository.ApplicationMetadataEntityCategoryEntitycategoriesCollection", "CategoryEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CategoryEntity>("AppRepository.ApplicationMetadataEntityCategoryEntitycategoriesCollection", "CategoryEntity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppRepository", Name="ApplicationVersionEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationVersionEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationVersionEntity object.
        /// </summary>
        /// <param name="applicationVersionID">Initial value of the applicationVersionID property.</param>
        public static ApplicationVersionEntity CreateApplicationVersionEntity(global::System.Int32 applicationVersionID)
        {
            ApplicationVersionEntity applicationVersionEntity = new ApplicationVersionEntity();
            applicationVersionEntity.applicationVersionID = applicationVersionID;
            return applicationVersionEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 applicationVersionID
        {
            get
            {
                return _applicationVersionID;
            }
            set
            {
                if (_applicationVersionID != value)
                {
                    OnapplicationVersionIDChanging(value);
                    ReportPropertyChanging("applicationVersionID");
                    _applicationVersionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("applicationVersionID");
                    OnapplicationVersionIDChanged();
                }
            }
        }
        private global::System.Int32 _applicationVersionID;
        partial void OnapplicationVersionIDChanging(global::System.Int32 value);
        partial void OnapplicationVersionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _timestamp;
        partial void OntimestampChanging(Nullable<global::System.DateTime> value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String versionString
        {
            get
            {
                return _versionString;
            }
            set
            {
                OnversionStringChanging(value);
                ReportPropertyChanging("versionString");
                _versionString = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("versionString");
                OnversionStringChanged();
            }
        }
        private global::System.String _versionString;
        partial void OnversionStringChanging(global::System.String value);
        partial void OnversionStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> acceptanceResult
        {
            get
            {
                return _acceptanceResult;
            }
            set
            {
                OnacceptanceResultChanging(value);
                ReportPropertyChanging("acceptanceResult");
                _acceptanceResult = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("acceptanceResult");
                OnacceptanceResultChanged();
            }
        }
        private Nullable<global::System.Int32> _acceptanceResult;
        partial void OnacceptanceResultChanging(Nullable<global::System.Int32> value);
        partial void OnacceptanceResultChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AppRepository", "ApplicationVersionEntityStringfilePathsCollection", "StringfilePathsEntity")]
        public EntityCollection<StringfilePathsEntity> filePaths
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StringfilePathsEntity>("AppRepository.ApplicationVersionEntityStringfilePathsCollection", "StringfilePathsEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StringfilePathsEntity>("AppRepository.ApplicationVersionEntityStringfilePathsCollection", "StringfilePathsEntity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppRepository", Name="CategoryEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoryEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoryEntity object.
        /// </summary>
        /// <param name="categoryName">Initial value of the categoryName property.</param>
        public static CategoryEntity CreateCategoryEntity(global::System.String categoryName)
        {
            CategoryEntity categoryEntity = new CategoryEntity();
            categoryEntity.categoryName = categoryName;
            return categoryEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoryName
        {
            get
            {
                return _categoryName;
            }
            set
            {
                if (_categoryName != value)
                {
                    OncategoryNameChanging(value);
                    ReportPropertyChanging("categoryName");
                    _categoryName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("categoryName");
                    OncategoryNameChanged();
                }
            }
        }
        private global::System.String _categoryName;
        partial void OncategoryNameChanging(global::System.String value);
        partial void OncategoryNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AppRepository", Name="StringfilePathsEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StringfilePathsEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StringfilePathsEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static StringfilePathsEntity CreateStringfilePathsEntity(global::System.Int32 id)
        {
            StringfilePathsEntity stringfilePathsEntity = new StringfilePathsEntity();
            stringfilePathsEntity.Id = id;
            return stringfilePathsEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String filePaths
        {
            get
            {
                return _filePaths;
            }
            set
            {
                OnfilePathsChanging(value);
                ReportPropertyChanging("filePaths");
                _filePaths = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("filePaths");
                OnfilePathsChanged();
            }
        }
        private global::System.String _filePaths;
        partial void OnfilePathsChanging(global::System.String value);
        partial void OnfilePathsChanged();

        #endregion
    
    }

    #endregion
    
}
