//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CodeVerifier
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CodeVerifierContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CodeVerifierContainer object using the connection string found in the 'CodeVerifierContainer' section of the application configuration file.
        /// </summary>
        public CodeVerifierContainer() : base("name=CodeVerifierContainer", "CodeVerifierContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CodeVerifierContainer object.
        /// </summary>
        public CodeVerifierContainer(string connectionString) : base(connectionString, "CodeVerifierContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CodeVerifierContainer object.
        /// </summary>
        public CodeVerifierContainer(EntityConnection connection) : base(connection, "CodeVerifierContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
